const CONFIG={weddingDate:'2027-04-17T17:00:00-06:00',mapsUrl:'https://maps.google.com',apiUrl:''};
const params=new URLSearchParams(location.search);const guestName=params.get('nombre')||'Invitado especial';const spots=Math.max(1,Math.min(10,Number(params.get('lugares'))||2));const inviteId=params.get('id')||'DEMO';
const greeting=document.getElementById('guestGreeting');greeting.textContent=`${guestName}, hemos reservado ${spots} ${spots===1?'lugar':'lugares'} para ti${spots===1?'':'/ustedes'}.`;
const attendees=document.getElementById('attendees');for(let i=1;i<=spots;i++){const o=document.createElement('option');o.value=i;o.textContent=i;attendees.appendChild(o)}document.getElementById('spotsHelp').textContent=`Máximo permitido: ${spots}`;
const statusInputs=[...document.querySelectorAll('input[name="status"]')];function syncAttendance(){const selected=document.querySelector('input[name="status"]:checked');const field=document.getElementById('attendanceField');if(selected&&selected.value==='No asistirá'){field.style.display='none';attendees.value='1'}else{field.style.display='block'}}statusInputs.forEach(i=>i.addEventListener('change',syncAttendance));
function tick(){const target=new Date(CONFIG.weddingDate).getTime();const diff=Math.max(0,target-Date.now());const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;days.textContent=d;hours.textContent=String(h).padStart(2,'0');minutes.textContent=String(m).padStart(2,'0');seconds.textContent=String(s).padStart(2,'0')}tick();setInterval(tick,1000);
document.getElementById('mapsButton').href=CONFIG.mapsUrl;
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('rsvpForm').addEventListener('submit',async e=>{e.preventDefault();const status=document.querySelector('input[name="status"]:checked')?.value;const payload={id:inviteId,nombre:guestName,estado:status,asistentes:status==='Confirmado'?Number(attendees.value):0,mensaje:document.getElementById('message').value.trim(),fecha:new Date().toISOString()};const btn=document.getElementById('submitButton'),msg=document.getElementById('formMessage');btn.disabled=true;btn.textContent='Guardando...';try{if(!CONFIG.apiUrl){await new Promise(r=>setTimeout(r,500));localStorage.setItem(`rsvp-${inviteId}`,JSON.stringify(payload));msg.textContent='Respuesta guardada en modo demo. Cuando conectemos Google Sheets se actualizará automáticamente.'}else{const res=await fetch(CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('No se pudo guardar');msg.textContent='¡Gracias! Tu respuesta fue registrada correctamente.'}}catch(err){msg.textContent='No pudimos guardar tu respuesta. Intenta de nuevo.'}finally{btn.disabled=false;btn.textContent='Guardar respuesta'}});
